@startuml
skinparam componentStyle uml1

database "players"
[PlayerController] --(getPlayerById
[PlayerController] --(savePlayer

[PlayerService] --(getReferenceById
[PlayerService] --(save
getPlayerById -- [PlayerService]
savePlayer -- [PlayerService]

[PlayerJpaRepository] --("players"
getReferenceById -- [PlayerJpaRepository]
save --[PlayerJpaRepository]

@enduml
