@startuml

database "players"
[PlayerJpaRepository] -("players"
getReferenceById - [PlayerJpaRepository]

[PlayerService] -(getReferenceById
getPlayerById - [PlayerService]

[PlayerController] -(getPlayerById

@enduml
